using Microsoft.EntityFrameworkCore;
using TenantPlatform.Core.Leasing;
using TenantPlatform.Web.Services.Agreements;
namespace TenantPlatform.Web.Services.Leasing;
public sealed record LeasingFollowupPage(List<LeasingFollowup> Rows,int Count,int Page,Dictionary<Guid,string> Names,List<LeasingNotification> Notifications,Dictionary<Guid,LeasingFollowup> NotificationTasks);
public sealed partial class LeasingService
{
    public async Task<List<LeasingNotification>> LeasingNotificationHistoryAsync(Guid account,CancellationToken ct=default){await using var db=await factory.CreateDbContextAsync(ct);var(_,admin)=await Member(db,account,ct);if(!admin)throw new UnauthorizedAccessException();return await db.LeasingNotifications.AsNoTracking().Where(x=>x.AccountId==account).OrderByDescending(x=>x.ScheduledUtc).Take(200).ToListAsync(ct);}
    public async Task<LeasingNotificationSettings> GetLeasingNotificationSettingsAsync(Guid account,CancellationToken ct=default){await using var db=await factory.CreateDbContextAsync(ct);var(_,admin)=await Member(db,account,ct);if(!admin)throw new UnauthorizedAccessException();return await db.LeasingNotificationSettings.AsNoTracking().SingleOrDefaultAsync(x=>x.AccountId==account,ct)??new(){AccountId=account,TimeZoneId=await db.AgreementReminderSettings.Where(x=>x.AccountId==account).Select(x=>x.TimeZoneId).SingleOrDefaultAsync(ct)??"Europe/Oslo"};}
    public async Task SaveLeasingNotificationSettingsAsync(Guid account,LeasingNotificationSettings input,string reason,CancellationToken ct=default)
    {
        await using var db=await factory.CreateDbContextAsync(ct);var(user,admin)=await Member(db,account,ct);if(!admin)throw new UnauthorizedAccessException();await using var tx=await db.Database.BeginTransactionAsync(ct);await Lock(db,account,ct);Reason(reason,true);AgreementTimeZones.Validate(input.TimeZoneId);var days=AgreementReminderSchedule.ValidateDays(input.Days);
        if(input.ExtraRecipientIds.Length>100||await db.UserAccounts.CountAsync(x=>x.AccountId==account&&x.User.IsActive&&input.ExtraRecipientIds.Contains(x.UserId),ct)!=input.ExtraRecipientIds.Distinct().Count())throw new LeasingValidationException("LifeInvalidOwner");
        var s=await db.LeasingNotificationSettings.SingleOrDefaultAsync(x=>x.AccountId==account,ct)??new(){AccountId=account};CheckRevision(s.Revision,input.Revision,true);var before=Snapshot(s);if(input.Enabled&&!s.Enabled)s.ActivatedUtc=clock.GetUtcNow();s.Enabled=input.Enabled;s.Days=days;s.TimeZoneId=input.TimeZoneId;s.ExtraRecipientIds=input.ExtraRecipientIds.Distinct().ToArray();s.Revision=Guid.NewGuid();if(db.Entry(s).State==EntityState.Detached)db.LeasingNotificationSettings.Add(s);PaymentEvent(db,account,null,null,user,"LifecycleNotifications",reason,before,Snapshot(s),Guid.NewGuid());await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);
    }
    public async Task<LeasingFollowupPage> ListLeasingFollowupsAsync(Guid account,LeasingFollowupKind? kind=null,LeasingFollowupStatus? status=null,DateOnly? to=null,Guid? owner=null,int page=1,CancellationToken ct=default)
    {
        await using var db=await factory.CreateDbContextAsync(ct);var(user,admin)=await Member(db,account,ct);var elevated=await LifecycleReader(admin,ct);var acquisitions=Acquisitions(db,account,user,elevated).Select(x=>x.Id);var frameworks=Frameworks(db,account,user,elevated).Select(x=>x.Id);
        await new LeasingLifecycleProcessor(factory,clock).RunAccountAsync(account,ct);
        var query=db.LeasingFollowups.AsNoTracking().Where(x=>x.AccountId==account&&(x.AcquisitionId.HasValue&&acquisitions.Contains(x.AcquisitionId.Value)||x.FrameworkId.HasValue&&frameworks.Contains(x.FrameworkId.Value)));
        if(kind.HasValue)query=query.Where(x=>x.Kind==kind);if(status.HasValue)query=query.Where(x=>x.Status==status);else query=query.Where(x=>x.Status!=LeasingFollowupStatus.Obsolete);if(to.HasValue)query=query.Where(x=>x.DueDate==null||x.DueDate<=to);if(owner.HasValue)query=query.Where(x=>x.OwnerUserId==owner);
        var count=await query.CountAsync(ct);page=Math.Clamp(page,1,Math.Max(1,(count+49)/50));var rows=await query.OrderBy(x=>x.DueDate).ThenBy(x=>x.Id).Skip((page-1)*50).Take(50).ToListAsync(ct);
        var names=await Acquisitions(db,account,user,elevated).AsNoTracking().ToDictionaryAsync(x=>x.Id,x=>x.Name,ct);foreach(var f in await Frameworks(db,account,user,elevated).AsNoTracking().ToListAsync(ct))names[f.Id]=f.Name;
        var visibleTasks=db.LeasingFollowups.Where(x=>x.AccountId==account&&(x.AcquisitionId.HasValue&&acquisitions.Contains(x.AcquisitionId.Value)||x.FrameworkId.HasValue&&frameworks.Contains(x.FrameworkId.Value))).Select(x=>x.Id);
        var notes=await db.LeasingNotifications.AsNoTracking().Where(x=>x.AccountId==account&&x.RecipientUserId==user&&x.Status==LeasingNotificationStatus.Delivered&&visibleTasks.Contains(x.FollowupId)).OrderByDescending(x=>x.DeliveredUtc).Take(100).ToListAsync(ct);
        var noteIds=notes.Select(x=>x.FollowupId).ToArray();return new(rows,count,page,names,notes,await db.LeasingFollowups.AsNoTracking().Where(x=>x.AccountId==account&&noteIds.Contains(x.Id)).ToDictionaryAsync(x=>x.Id,ct));
    }
    public async Task UpdateLeasingFollowupAsync(Guid account,Guid id,Guid revision,LeasingFollowupStatus status,Guid? owner,string comment,Guid request,CancellationToken ct=default)
    {
        await using var db=await factory.CreateDbContextAsync(ct);var(user,admin)=await Member(db,account,ct);await using var tx=await db.Database.BeginTransactionAsync(ct);await Lock(db,account,ct);var task=await db.LeasingFollowups.SingleOrDefaultAsync(x=>x.AccountId==account&&x.Id==id,ct)??throw new UnauthorizedAccessException();
        if(!await LeasingLifecycleAccess.CanRead(db,account,user,task.AcquisitionId,task.FrameworkId,ct))throw new UnauthorizedAccessException();
        var canManage=admin||await authorization.CanManageLeasingLifecycleAsync(ct)||(task.AcquisitionId.HasValue?await Acquisitions(db,account,user,false).AnyAsync(x=>x.Id==task.AcquisitionId,ct):await Frameworks(db,account,user,false).AnyAsync(x=>x.Id==task.FrameworkId,ct));if(!canManage)throw new UnauthorizedAccessException();
        if(await PaymentRetry(db,account,request,user,"LifecycleTask",task.AcquisitionId,null,ct))return;CheckRevision(task.Revision,revision,true);Reason(comment,true);if(status is not(LeasingFollowupStatus.Open or LeasingFollowupStatus.InProgress or LeasingFollowupStatus.Completed)||task.Status==LeasingFollowupStatus.Obsolete)throw new LeasingValidationException("LeasingInvalidTransition");if(owner.HasValue&&!await LeasingLifecycleAccess.CanRead(db,account,owner.Value,task.AcquisitionId,task.FrameworkId,ct))throw new LeasingValidationException("LifeInvalidOwner");
        var before=Snapshot(task);task.OwnerUserId=owner;task.AssignedExplicitly=true;task.Status=status;task.Comment=comment;task.CompletedByUserId=status==LeasingFollowupStatus.Completed?user:null;task.CompletedUtc=status==LeasingFollowupStatus.Completed?clock.GetUtcNow():null;task.Revision=Guid.NewGuid();PaymentEvent(db,account,task.AcquisitionId,null,user,"LifecycleTask",comment,before,Snapshot(task),request);await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);
    }
    public async Task ReadLeasingNotificationAsync(Guid account,Guid id,CancellationToken ct=default){await using var db=await factory.CreateDbContextAsync(ct);var(user,_)=await Member(db,account,ct);var n=await db.LeasingNotifications.SingleOrDefaultAsync(x=>x.AccountId==account&&x.Id==id&&x.RecipientUserId==user,ct)??throw new UnauthorizedAccessException();var task=await db.LeasingFollowups.SingleAsync(x=>x.AccountId==account&&x.Id==n.FollowupId,ct);if(!await LeasingLifecycleAccess.CanRead(db,account,user,task.AcquisitionId,task.FrameworkId,ct))throw new UnauthorizedAccessException();n.ReadUtc??=clock.GetUtcNow();await db.SaveChangesAsync(ct);}
}
