using Microsoft.EntityFrameworkCore;
using TenantPlatform.Core.Agreements;
using TenantPlatform.Infrastructure.Persistence;
using TenantPlatform.Web.Services.Agreements;

static class BulkBasisChecks
{
    public static async Task Run(IDbContextFactory<TenantPlatformDbContext> factory, AgreementService admin,
        AgreementService owner, AgreementService reader, AgreementService foreign, Guid account, Guid otherAccount,
        Guid ownerId, Guid readerId, Guid org, Guid foreignOrg, Guid foreignId)
    {
        var from = new DateOnly(2027, 1, 1); var to = new DateOnly(2027, 1, 31);
        SaveAgreementRequest Request(string title, string currency = "NOK", AgreementDirection direction = AgreementDirection.Income) =>
            new() { Title = title, Form = AgreementForm.Renewing, RenewalDate = new(2035, 1, 1), StartDate = from,
                OwnerUserId = ownerId, CounterpartyOrganizationId = org, Direction = direction, Currency = currency, Status = AgreementStatus.Active };
        SaveAgreementLineRequest Line(AgreementFrequency frequency = AgreementFrequency.Monthly) =>
            new() { Name = "Bulk " + frequency, StartDate = from, FirstPayableDate = from, AnchorDate = from,
                EffectiveFrom = from, UnitPrice = 1000, Activate = true, Frequency = frequency };
        async Task<Guid> Save(Guid id, Guid? lineId, SaveAgreementLineRequest line)
        {
            line.Revision = (await owner.GetAsync(account, id)).Revision;
            return await owner.SaveLineAsync(account, id, lineId, line);
        }
        async Task<AgreementBulkBasisPreview> Preview(Guid id) => (await owner.PreviewBulkBasisAsync(account, new(from, to, AgreementId: id))).Single();
        AgreementBulkBasisSelection Pick(AgreementBulkBasisPreview row) => new(row.AgreementId, row.Fingerprint);
        var monthly = await admin.CreateAsync(account, Request("Bulk monthly")); var monthlyLine = await Save(monthly, null, Line());
        var mixed = await admin.CreateAsync(account, Request("Bulk EUR frequencies", "EUR"));
        foreach (var frequency in new[] { AgreementFrequency.Monthly, AgreementFrequency.Quarterly, AgreementFrequency.Yearly, AgreementFrequency.Once }) await Save(mixed, null, Line(frequency));
        var cost = await admin.CreateAsync(account, Request("Bulk excluded cost", direction: AgreementDirection.Cost)); await Save(cost, null, Line());
        var empty = await admin.CreateAsync(account, Request("Bulk empty"));
        var invalid = await admin.CreateAsync(account, Request("Bulk missing currency"));
        var privateRequest = Request("Private agreement in same account"); privateRequest.OwnerUserId = readerId;
        var privateAgreement = await admin.CreateAsync(account, privateRequest);
        var ended = await admin.CreateAsync(account, Request("Bulk ended")); var endedLine = Line(); endedLine.EndDate = to; await Save(ended, null, endedLine);
        await using (var db = await factory.CreateDbContextAsync())
        {
            var a = await db.Agreements.SingleAsync(x => x.AccountId == account && x.Id == ended);
            a.Status = AgreementStatus.Expired; a.EndDate = to;
            (await db.Agreements.SingleAsync(x => x.AccountId == account && x.Id == invalid)).Currency = null;
            await db.SaveChangesAsync();
        }
        var foreignRequest = Request("Other account private"); foreignRequest.OwnerUserId = foreignId; foreignRequest.CounterpartyOrganizationId = foreignOrg;
        var foreignAgreement = await foreign.CreateAsync(otherAccount, foreignRequest);
        var options = await owner.GetBulkBasisOptionsAsync(account);
        Require(options.Any(x => x.Id == ended) && !options.Any(x => x.Id == cost || x.Id == foreignAgreement || x.Id == privateAgreement), "options include ended income agreements and exclude costs and other accounts");
        var partyFilter = await owner.PreviewBulkBasisAsync(account, new(from, to, Guid.NewGuid()));
        Require(partyFilter.Count == 0, "counterparty filter scopes preview");
        Require((await owner.PreviewBulkBasisAsync(account, new(from, to, AgreementId: foreignAgreement))).Count == 0, "foreign agreement filter reveals no data");
        var all = await owner.PreviewBulkBasisAsync(account, new(from, to, org));
        Require(all.Any(x => x.AgreementId == monthly && x.CanGenerate) && all.Any(x => x.AgreementId == mixed && x.CanGenerate), "multiple income agreements preview together");
        Require(all.Single(x => x.AgreementId == invalid).Reason == "FinanceSetupRequired", "invalid agreement gives concrete error without stopping other previews");
        Require((await owner.GenerateBulkBasisAsync(account, from, to, [new(privateAgreement, "forged")])).Single().Reason == "BulkAccessDenied", "same-account private agreement cannot be generated by forged selection");
        var accountDenied = false;
        try { await owner.GenerateBulkBasisAsync(otherAccount, from, to, [new(foreignAgreement, "forged")]); }
        catch (UnauthorizedAccessException) { accountDenied = true; }
        Require(accountDenied, "client cannot switch account boundary");
        Require(all.Single(x => x.AgreementId == empty).Status == AgreementBulkBasisStatus.Empty, "empty agreement explicitly reported");
        Require(all.Single(x => x.AgreementId == ended).CanGenerate, "expired agreement with unprocessed periods remains eligible");
        var p1 = await Preview(monthly); var p2 = await Preview(mixed);
        var single = await owner.PreviewBasisAsync(account, mixed, AgreementDirection.Income, from, to);
        Require(System.Text.Json.JsonSerializer.Serialize(p2.Periods) == System.Text.Json.JsonSerializer.Serialize(single.Periods) && p2.LineCount == 4 && p2.BasisCount == 1 && p2.Amount == 4000, "monthly quarterly annual and one-off lines reuse single-agreement invoice semantics");
        await using (var db = await factory.CreateDbContextAsync())
            Require(!await db.AgreementBasisRecords.AnyAsync(x => x.AccountId == account && new[] { monthly, mixed, ended }.Contains(x.AgreementId)), "bulk preview creates no bases");
        var selected = await owner.GenerateBulkBasisAsync(account, from, to, [Pick(p1), Pick(p1)]);
        Require(selected.Count == 1 && selected[0].Created.Count == 1 && selected[0].Created[0].Amount == 1000, "subset and duplicate selections generate only the selected agreement once");
        Require((await Preview(mixed)).Status == AgreementBulkBasisStatus.Ready, "unselected agreement is unchanged");
        var rerun = await owner.GenerateBulkBasisAsync(account, from, to, [Pick(p1)]);
        Require(rerun.Single().Created.Count == 0 && rerun.Single().Existing.Count == 1, "same preview retry reuses unchanged basis");
        Require((await Preview(monthly)).Status == AgreementBulkBasisStatus.Existing, "preview reports already generated");
        var concurrent = await Task.WhenAll(owner.GenerateBulkBasisAsync(account, from, to, [Pick(p2)]), owner.GenerateBulkBasisAsync(account, from, to, [Pick(p2)]));
        Require(concurrent.SelectMany(x => x).Sum(x => x.Created.Count) == 1 && concurrent.SelectMany(x => x).Sum(x => x.Existing.Count) == 1, "concurrent bulk runs create no duplicate");
        var approvedId = selected.Single().Created.Single().Id; await owner.ApproveBasisAsync(account, approvedId, 1);
        var approvedJson = (await owner.GetBasisAsync(account, approvedId)).Snapshots[0].DataJson;
        var edit = Line(); edit.UnitPrice = 1500; edit.Reason = "Bulk price correction"; await Save(monthly, monthlyLine, edit);
        var changed = await owner.GenerateBulkBasisAsync(account, from, to, [Pick(p1)]);
        Require(changed.Single().Reason == "BulkChanged", "changed financial data require new preview");
        Require((await Preview(monthly)).Reason == "ProcessingCorrectionNeeded", "changed approved basis requires correction");
        Require((await owner.GetBasisAsync(account, approvedId)).Snapshots[0].DataJson == approvedJson, "bulk flow preserves approved snapshot");
        var mixedLine = (await owner.GetLinesAsync(account, mixed)).Lines.First(x => x.Versions[0].Frequency == AgreementFrequency.Monthly).Line.Id;
        await Save(mixed, mixedLine, edit);
        var stalePreview = await Preview(mixed);
        Require(stalePreview.Reason == "BulkStaleDraft", "outdated drafts explicitly require follow-up");
        var endedPreview = await Preview(ended);
        var partial = await owner.GenerateBulkBasisAsync(account, from, to, [Pick(stalePreview), new(foreignAgreement, "forged"), new(cost, "forged"), Pick(endedPreview)]);
        Require(partial.Take(3).All(x => x.Status == AgreementBulkBasisStatus.Followup) && partial.Last().Created.Count == 1, "stale draft inaccessible and cost agreements do not roll back a valid agreement");
        Require(partial[1].Reason == "BulkAccessDenied" && partial[2].Reason == "ProcessingWrongDirection", "server revalidates agreement identifiers and direction");
        var mixedBasis = concurrent.SelectMany(x => x).SelectMany(x => x.Created).Single().Id;
        await owner.RegenerateBasisAsync(account, mixedBasis, 1, "Resolve stale draft");
        var retried = await owner.GenerateBulkBasisAsync(account, from, to, [Pick(await Preview(mixed))]);
        Require(retried.Single().Existing.Count == 1 && retried.Single().Created.Count == 0, "failed agreement can be retried after follow-up without duplicate");
        await owner.SetAccessAsync(account, empty, readerId, AgreementAccessLevel.Read, (await owner.GetAsync(account, empty)).Revision);
        var readPreview = (await reader.PreviewBulkBasisAsync(account, new(from, to, AgreementId: empty))).Single();
        Require(!readPreview.CanGenerate && readPreview.Reason == "BulkReadOnly", "read-only access allows preview but not selection");
        var rejected = await reader.GenerateBulkBasisAsync(account, from, to, [Pick(readPreview)]);
        Require(rejected.Single().Reason == "BulkAccessDenied", "server enforces edit permission");
        await owner.SetAccessAsync(account, empty, readerId, AgreementAccessLevel.Edit, (await owner.GetAsync(account, empty)).Revision);
        var beforeRevoked = (await reader.PreviewBulkBasisAsync(account, new(from, to, AgreementId: empty))).Single();
        await owner.SetAccessAsync(account, empty, readerId, null, (await owner.GetAsync(account, empty)).Revision);
        Require((await reader.GenerateBulkBasisAsync(account, from, to, [Pick(beforeRevoked)])).Single().Reason == "BulkAccessDenied", "revoked rights are checked after preview");
        var fresh = await admin.CreateAsync(account, Request("Bulk changed before first generation")); var freshLine = await Save(fresh, null, Line());
        var oldPreview = await Preview(fresh); await Save(fresh, freshLine, edit);
        Require((await owner.GenerateBulkBasisAsync(account, from, to, [Pick(oldPreview)])).Single().Reason == "BulkChanged", "change before first generation produces no stale draft");
        await using (var db = await factory.CreateDbContextAsync())
            Require(!await db.AgreementBasisRecords.AnyAsync(x => x.AccountId == account && x.AgreementId == fresh), "rejected change leaves no new basis");
        var otherRange = await owner.GenerateBulkBasisAsync(account, from.AddMonths(1), to.AddMonths(1), [Pick(oldPreview)]);
        Require(otherRange.Single().Reason == "BulkChanged", "preview fingerprint is tied to invoice range");
        var cancelledPreview = await Preview(ended);
        await owner.CancelBasisAsync(account, partial.Last().Created.Single().Id, 1, "Cancel for replacement");
        Require((await owner.GenerateBulkBasisAsync(account, from, to, [Pick(cancelledPreview)])).Single().Reason == "BulkChanged", "cancellation after preview requires previewing the increased new amount");
        var race = await admin.CreateAsync(account, Request("Bulk and single race")); await Save(race, null, Line());
        var racePreview = await Preview(race);
        var bulkRace = owner.GenerateBulkBasisAsync(account, from, to, [Pick(racePreview)]);
        var singleRace = owner.GenerateBasisAsync(account, race, AgreementDirection.Income, from, to);
        await Task.WhenAll(bulkRace, singleRace);
        Require(bulkRace.Result.Single().Created.Count + singleRace.Result.Created.Count == 1, "single and bulk generation share duplicate protection");
        var index = await admin.CreateIndexAsync(account, "BULKINDEX", "Bulk index", "", "Test", AgreementIndexResolution.Year);
        await admin.RecordIndexValueAsync(account, index, new(2026, 1, 1), 101, null, "Base");
        await admin.RecordIndexValueAsync(account, index, from, 105, null, "Next");
        var indexRequest = Request("Bulk revised index"); indexRequest.IndexId = index; indexRequest.StartDate = new(2026, 1, 1);
        var indexed = await admin.CreateAsync(account, indexRequest);
        var indexLine = Line(); indexLine.StartDate = indexLine.FirstPayableDate = indexLine.AnchorDate = indexLine.EffectiveFrom = new(2026, 1, 1); indexLine.IndexRegulated = true;
        await Save(indexed, null, indexLine);
        var indexPreview = await Preview(indexed);
        Require(indexPreview.Periods.Single().UnitPrice == 1039.60m, "bulk preview applies automatic index regulation");
        var level = (await admin.GetIndicesAsync(account)).Values.Single(x => x.IndexId == index && x.Period == from);
        await admin.RecordIndexValueAsync(account, index, from, 106, null, "Revised", level.Id);
        Require((await owner.GenerateBulkBasisAsync(account, from, to, [Pick(indexPreview)])).Single().Reason == "BulkChanged", "index revisions after preview are detected");
        var currentIndexPreview = await Preview(indexed);
        var indexRun = (await owner.GenerateBulkBasisAsync(account, from, to, [Pick(currentIndexPreview)])).Single();
        var indexBasis = await owner.GetBasisAsync(account, indexRun.Created.Single().Id);
        Require(indexBasis.Basis.Status == AgreementBasisStatus.Draft && indexRun.Created.Single().Amount == 1049.50m, "bulk creates only drafts with current index amount");
        var context = new UserContext(ownerId, account);
        await ComponentEditorChecks.BulkNavigation(owner, context, new TenantPlatform.Web.Security.Authorization.TenantAuthorizationService(factory, context));
        var uiNok = await admin.CreateAsync(account, Request("UI bulk NOK")); await Save(uiNok, null, Line());
        var uiEur = await admin.CreateAsync(account, Request("UI bulk EUR", "EUR")); await Save(uiEur, null, Line());
        await ComponentEditorChecks.Bulk(owner, new UserContext(ownerId, account), uiNok, uiEur, from, to);
    }
    static void Require(bool condition, string name) { if (!condition) throw new Exception("FAIL BULK: " + name); Console.WriteLine("PASS BULK: " + name); }
}
