// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TenantPlatform.Infrastructure.Persistence;

#nullable disable

namespace TenantPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TenantPlatformDbContext))]
    [Migration("20260916154805_AddAgreementFollowupAndReminders")]
    partial class AddAgreementFollowupAndReminders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TenantPlatform.Core.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.Agreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounterpartyOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DeadlinesInitialized")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("NoticeDeadline")
                        .HasColumnType("date");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("ReminderDays")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("ReminderMode")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("RenewalDate")
                        .HasColumnType("date");

                    b.Property<int?>("RenewalMonths")
                        .HasColumnType("integer");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Terms")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CounterpartyOrganizationId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("UnitId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("AccountId", "NoticeDeadline");

                    b.HasIndex("AccountId", "OwnerUserId");

                    b.HasIndex("AccountId", "Status", "Type");

                    b.ToTable("agreements", null, t =>
                        {
                            t.HasCheckConstraint("CK_agreements_dates", "\"EndDate\" IS NULL OR \"EndDate\" >= \"StartDate\"");

                            t.HasCheckConstraint("CK_agreements_renewal", "\"RenewalMonths\" IS NULL OR (\"AutoRenew\" AND \"RenewalMonths\" > 0)");

                            t.HasCheckConstraint("CK_agreements_status", "\"Status\" IN (1,2,3,4)");

                            t.HasCheckConstraint("CK_agreements_type", "\"Type\" IN (1,2,3,4,5)");

                            t.HasCheckConstraint("CK_agreements_unit_building", "\"UnitId\" IS NULL OR \"BuildingId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("AccountId", "UserId");

                    b.HasIndex("AccountId", "AgreementId", "UserId")
                        .IsUnique();

                    b.ToTable("agreement_access", null, t =>
                        {
                            t.HasCheckConstraint("CK_agreement_access_level", "\"Level\" IN (1,2)");
                        });
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementDeadline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("PeriodStartDate")
                        .HasColumnType("date");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("AccountId", "AgreementId", "State");

                    b.HasIndex("AccountId", "State", "Status", "DueDate");

                    b.ToTable("agreement_deadlines", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementDeadlineHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeadlineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("AccountId", "DeadlineId", "CreatedUtc");

                    b.ToTable("agreement_deadline_history", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgreementId")
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UploadedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("AccountId", "AgreementId", "UploadedUtc");

                    b.ToTable("agreement_documents", null, t =>
                        {
                            t.HasCheckConstraint("CK_agreement_documents_category", "\"Category\" IN (1,2)");

                            t.HasCheckConstraint("CK_agreement_documents_size", "\"Size\" > 0");
                        });
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementReminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<int>("DaysBefore")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeadlineId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextAttemptUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("RecipientUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReservationId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReservedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ScheduledUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SentUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("TransportId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("AccountId", "DeadlineId", "DaysBefore")
                        .IsUnique();

                    b.HasIndex("AccountId", "Status", "NextAttemptUtc");

                    b.ToTable("agreement_reminders", null, t =>
                        {
                            t.HasCheckConstraint("CK_agreement_reminder_days", "\"DaysBefore\" >= 0");
                        });
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementReminderSettings", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<int[]>("Days")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("SendAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("AccountId");

                    b.ToTable("agreement_reminder_settings", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChangesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.LoginAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LastAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("login_accounts", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "AccountId")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.UserAccountRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("UserAccountId", "OrganizationId", "BuildingId", "Role")
                        .IsUnique();

                    b.ToTable("user_account_roles", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.CalendarIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("calendar_integrations", null, t =>
                        {
                            t.HasCheckConstraint("CK_calendar_integrations_provider", "\"Provider\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.MeetingRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("AccountId", "BuildingId");

                    b.ToTable("meeting_rooms", null, t =>
                        {
                            t.HasCheckConstraint("CK_meeting_rooms_capacity", "\"Capacity\" IS NULL OR \"Capacity\" > 0");
                        });
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.MeetingRoomCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CalendarIntegrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExternalCalendarId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ExternalResourceEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("MeetingRoomId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "MeetingRoomId")
                        .IsUnique();

                    b.HasIndex("AccountId", "CalendarIntegrationId", "ExternalCalendarId")
                        .IsUnique();

                    b.ToTable("meeting_room_calendars", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.RoomBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MeetingRoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerUserId");

                    b.HasIndex("AccountId", "MeetingRoomId", "StartUtc", "EndUtc");

                    b.ToTable("room_bookings", null, t =>
                        {
                            t.HasCheckConstraint("CK_room_bookings_interval", "\"EndUtc\" > \"StartUtc\"");

                            t.HasCheckConstraint("CK_room_bookings_status", "\"Status\" IN (1, 2)");
                        });
                });

            modelBuilder.Entity("TenantPlatform.Core.Networking.NetworkEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Vendor")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BuildingId", "Name")
                        .IsUnique();

                    b.ToTable("network_environments", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Networking.NetworkSsid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBroadcast")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("NetworkEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("SecurityType")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("VlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantOrganizationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("AccountId", "Name")
                        .IsUnique();

                    b.ToTable("network_ssids", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Networking.SsidRequestDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExistingNetworkSsidId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NetworkEnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("RequestedIsBroadcast")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestedName")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("RequestedSecurityType")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestedVlanId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExistingNetworkSsidId");

                    b.HasIndex("NetworkEnvironmentId");

                    b.HasIndex("ServiceRequestId")
                        .IsUnique();

                    b.ToTable("ssid_request_details", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Occupancies.Occupancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TenantOrganizationId");

                    b.HasIndex("UnitId");

                    b.HasIndex("TenantOrganizationId", "UnitId", "ValidFrom");

                    b.ToTable("occupancies", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrganizationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "OrganizationNumber");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Properties.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Properties.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentUnitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ParentUnitId");

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InReplyToMessageId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("References")
                        .HasColumnType("text");

                    b.Property<string>("ReplyToAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToAddress")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("email_outbox_messages", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("HandlerType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBookableByTenant")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresOccupancy")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "Category");

                    b.HasIndex("AccountId", "Code")
                        .IsUnique();

                    b.ToTable("service_definitions", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Options")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId", "Key")
                        .IsUnique();

                    b.HasIndex("ServiceDefinitionId", "SortOrder");

                    b.ToTable("service_definition_fields", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionFieldTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ServiceDefinitionFieldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionFieldId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("service_definition_field_translations", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntegrationType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("RequestEmailAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceProviderOrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ServiceProviderOrganizationId");

                    b.HasIndex("ServiceDefinitionId", "ServiceProviderOrganizationId")
                        .IsUnique();

                    b.HasIndex("AccountId", "ServiceDefinitionId", "ServiceProviderOrganizationId")
                        .IsUnique();

                    b.ToTable("service_definition_providers", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId");

                    b.HasIndex("ServiceDefinitionId", "LanguageCode")
                        .IsUnique();

                    b.ToTable("service_definition_translations", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedServiceProviderOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplyToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RequesterOrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AssignedServiceProviderOrganizationId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ReplyToken")
                        .IsUnique();

                    b.HasIndex("RequesterOrganizationId");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("ServiceDefinitionId");

                    b.HasIndex("Status");

                    b.HasIndex("UnitId");

                    b.HasIndex("AccountId", "CreatedAt");

                    b.ToTable("service_requests", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceRequestFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceDefinitionFieldId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionFieldId");

                    b.HasIndex("ServiceRequestId", "ServiceDefinitionFieldId")
                        .IsUnique();

                    b.ToTable("service_request_field_values", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceRequestMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<int?>("EventType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalMessageId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalThreadId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("InReplyToMessageId")
                        .HasColumnType("text");

                    b.Property<string>("References")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ToAddress")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExternalMessageId")
                        .IsUnique();

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("ServiceRequestId", "CreatedAt");

                    b.ToTable("service_request_messages", (string)null);
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.Agreement", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("CounterpartyOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementAccess", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Agreements.Agreement", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "AgreementId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementDeadline", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Agreements.Agreement", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "AgreementId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementDeadlineHistory", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Agreements.AgreementDeadline", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "DeadlineId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementDocument", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Agreements.Agreement", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "AgreementId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementReminder", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Agreements.AgreementDeadline", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "DeadlineId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Agreements.AgreementReminderSettings", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.LoginAccount", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", "User")
                        .WithOne("LoginAccount")
                        .HasForeignKey("TenantPlatform.Core.Identity.LoginAccount", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.UserAccount", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", "Account")
                        .WithMany("Users")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Identity.User", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.UserAccountRole", b =>
                {
                    b.HasOne("TenantPlatform.Core.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Identity.UserAccount", "UserAccount")
                        .WithMany("UserAccountRoles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.CalendarIntegration", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.MeetingRoom", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.MeetingRoomCalendar", b =>
                {
                    b.HasOne("TenantPlatform.Core.MeetingRooms.CalendarIntegration", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "CalendarIntegrationId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.MeetingRooms.MeetingRoom", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "MeetingRoomId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.MeetingRooms.RoomBooking", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("OrganizerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.MeetingRooms.MeetingRoom", null)
                        .WithMany()
                        .HasForeignKey("AccountId", "MeetingRoomId")
                        .HasPrincipalKey("AccountId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Networking.NetworkEnvironment", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Networking.NetworkSsid", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TenantPlatform.Core.Networking.SsidRequestDetails", b =>
                {
                    b.HasOne("TenantPlatform.Core.Networking.NetworkSsid", null)
                        .WithMany()
                        .HasForeignKey("ExistingNetworkSsidId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Networking.NetworkEnvironment", null)
                        .WithMany()
                        .HasForeignKey("NetworkEnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Services.ServiceRequest", null)
                        .WithOne()
                        .HasForeignKey("TenantPlatform.Core.Networking.SsidRequestDetails", "ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Occupancies.Occupancy", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("TenantOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Organizations.Organization", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Properties.Building", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Properties.Unit", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Unit", null)
                        .WithMany()
                        .HasForeignKey("ParentUnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.EmailOutboxMessage", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Services.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinition", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionField", b =>
                {
                    b.HasOne("TenantPlatform.Core.Services.ServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionFieldTranslation", b =>
                {
                    b.HasOne("TenantPlatform.Core.Services.ServiceDefinitionField", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionFieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionProvider", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Services.ServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("ServiceProviderOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceDefinitionTranslation", b =>
                {
                    b.HasOne("TenantPlatform.Core.Services.ServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceRequest", b =>
                {
                    b.HasOne("TenantPlatform.Core.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("AssignedServiceProviderOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Properties.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("RequesterOrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Services.ServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Properties.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceRequestFieldValue", b =>
                {
                    b.HasOne("TenantPlatform.Core.Services.ServiceDefinitionField", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenantPlatform.Core.Services.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Services.ServiceRequestMessage", b =>
                {
                    b.HasOne("TenantPlatform.Core.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenantPlatform.Core.Services.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenantPlatform.Core.Accounts.Account", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.User", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("LoginAccount");
                });

            modelBuilder.Entity("TenantPlatform.Core.Identity.UserAccount", b =>
                {
                    b.Navigation("UserAccountRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
