using System.Text;
using System.Text.Json;
using System.IO.Compression;
using System.Xml.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using TenantPlatform.Core.Accounts;
using TenantPlatform.Core.Identity;
using TenantPlatform.Core.Leasing;
using TenantPlatform.Core.Organizations;
using TenantPlatform.Infrastructure.Persistence;
using TenantPlatform.Web;
using TenantPlatform.Web.Security.Authorization;
using TenantPlatform.Web.Services.Leasing;
using TenantPlatform.Web.Services.Agreements;

static class LifecycleChecks
{
    public static async Task Run(IDbContextFactory<TenantPlatformDbContext> factory,Guid adminId,Guid ownerId,Guid outsiderId,Guid foreignAccount)
    {
        Check(LeasingLifecycleCalculator.Notice(new(2028,3,31),LeasingNoticeBasis.CalendarMonths,null,1)==new DateOnly(2028,2,29),"calendar-month notice preserves leap month-end");
        Check(LeasingLifecycleCalculator.Notice(new(2028,3,30),LeasingNoticeBasis.CalendarMonths,null,1)==new DateOnly(2028,2,29),"notice day clamps at month-end");
        Check(LeasingLifecycleCalculator.Notice(new(2028,3,31),LeasingNoticeBasis.Days,null,31)==new DateOnly(2028,2,29),"day-based notice uses calendar days");
        Check(LeasingLifecycleCalculator.Notice(new(2028,1,1),LeasingNoticeBasis.Unknown,null,null)==null,"unknown notice does not infer standard terms");
        Check(AgreementReminderSchedule.Today(new(2028,1,1,23,30,0,TimeSpan.Zero),"Europe/Oslo")==new DateOnly(2028,1,2),"account time-zone day boundary");
        var scheduled=AgreementReminderSchedule.Scheduled(new(2028,3,26),0,"Europe/Oslo",new(2,30));Check(TimeZoneInfo.ConvertTime(scheduled,AgreementReminderSchedule.Zone("Europe/Oslo")).Hour==3,"nonexistent DST wall time advances safely");
        var account=Guid.NewGuid();var party=Guid.NewGuid();var clock=new MutableClock{Now=new(2027,11,1,12,0,0,TimeSpan.Zero)};
        await using(var db=factory.CreateDbContext()){db.Accounts.Add(new(){Id=account,Name="Lifecycle tests"});db.Organizations.Add(new(){Id=party,AccountId=account,Name="Lifecycle finance"});foreach(var u in new[]{adminId,ownerId,outsiderId}){var m=new UserAccount{Id=Guid.NewGuid(),AccountId=account,UserId=u};db.UserAccounts.Add(m);if(u==adminId)db.UserAccountRoles.Add(new(){Id=Guid.NewGuid(),UserAccountId=m.Id,Role=UserRole.AccountAdmin});}await db.SaveChangesAsync();}
        LeasingService Service(Guid u){var c=new Context(u,account);return new(factory,c,new TenantAuthorizationService(factory,c),new MemoryStorage(),clock,NullLogger<LeasingService>.Instance);}
        var admin=Service(adminId);var owner=Service(ownerId);var outsider=Service(outsiderId);
        var frame=await admin.SaveFrameworkAsync(account,null,new(){Name="Expired window",Number="LC",OwnerUserId=ownerId,FinanceOrganizationId=party,AcquisitionFrom=new(2027,1,1),AcquisitionTo=new(2027,12,31),Limit=100000,Terms=new(){Months=12}},"");
        async Task<Guid> Buy(string name,string currency="NOK"){var a=await admin.NewAcquisitionAsync(account,currency=="NOK"?frame:null);a.Name=name;a.Reference=Guid.NewGuid().ToString();a.OwnerUserId=ownerId;a.SupplierOrganizationId=a.FinanceOrganizationId=party;a.Currency=currency;a.PurchaseDate=new(2027,1,1);a.Terms.Months=12;a.FinancedAmount=750;a.Status=LeasingAcquisitionStatus.Registered;a.Items=[new(){Description="Devices",Quantity=4,UnitPrice=250,VatPercent=25}];return await admin.SaveAcquisitionAsync(account,null,a,"");}
        var a1=await Buy("Operational lease");var a2=await Buy("Replacement purchase");var eur=await Buy("Euro lease","EUR");
        var order=await owner.SaveOrderAsync(account,null,new(){FrameworkId=frame,OwnerUserId=ownerId,SupplierOrganizationId=party,OrderDate=new(2027,11,1),Lines=[new(){Description="Reserved",Quantity=1,UnitPrice=2000}]},"",Guid.NewGuid());var od=await admin.GetOrderAsync(account,order);await admin.OrderActionAsync(account,order,od.Order.Revision,LeasingOrderStatus.Pending,"Submit",Guid.NewGuid());od=await admin.GetOrderAsync(account,order);await admin.OrderActionAsync(account,order,od.Order.Revision,LeasingOrderStatus.Approved,"Approve",Guid.NewGuid());
        var before=await admin.GetAsync(account,frame,true);clock.Now=new(2028,1,15,12,0,0,TimeSpan.Zero);var processor=new LeasingLifecycleProcessor(factory,clock);await Task.WhenAll(processor.RunAccountAsync(account),new LeasingLifecycleProcessor(factory,clock).RunAccountAsync(account));
        var initial=await admin.GetLifecycleAsync(account,a1);Check(initial.Lifecycle.Status==LeasingLifecycleStatus.Active&&initial.Lifecycle.OriginalEndDate==new DateOnly(2028,1,1),"expired historic leases stay active until explicit outcome");
        var tasks=await admin.ListLeasingFollowupsAsync(account);Check(tasks.Rows.Any(x=>x.Kind==LeasingFollowupKind.OpenReservation)&&tasks.Rows.Any(x=>x.AcquisitionId==a1&&x.Kind==LeasingFollowupKind.Expiry),"expired framework window exposes reservation and individual expiry follow-ups");Check((await admin.GetAsync(account,frame,true)).Reserved==before.Reserved,"expiry job never releases reservations");var taskCount=tasks.Count;await processor.RunAccountAsync(account);Check((await admin.ListLeasingFollowupsAsync(account)).Count==taskCount,"repeated/concurrent job does not duplicate tasks");
        await Deny(()=>outsider.GetLifecycleAsync(account,a1));await Deny(()=>admin.GetLifecycleAsync(foreignAccount,a1));await Deny(()=>outsider.SaveEquipmentAsync(account,a1,[],false,"No permission",Guid.NewGuid()));
        var f=(await admin.GetAsync(account,frame,true)).Framework!;f.Status=LeasingFrameworkStatus.Finished;await Reject(()=>admin.SaveFrameworkAsync(account,frame,f,"Close"),"LifeFrameworkUnresolved");
        async Task<LifecycleDetails> Details(Guid id)=>await admin.GetLifecycleAsync(account,id);
        var l=initial.Lifecycle;l.NoticeBasis=LeasingNoticeBasis.CalendarMonths;l.NoticeCount=1;l.AutomaticExtension=true;l.ExtensionMonths=12;l.ReturnDueDate=new(2028,2,15);await owner.SaveLifecycleTermsAsync(account,a1,l,"Documented notice",Guid.NewGuid());
        var settings=await admin.GetLeasingNotificationSettingsAsync(account);settings.Enabled=true;settings.Days=[30,7,0];settings.ExtraRecipientIds=[outsiderId];await admin.SaveLeasingNotificationSettingsAsync(account,settings,"Explicit activation");await processor.RunAccountAsync(account);
        await using(var db=factory.CreateDbContext()){Check(!await db.LeasingNotifications.AnyAsync(x=>x.AccountId==account&&x.Status==LeasingNotificationStatus.Delivered),"activation sends no historical backlog");Check(await db.LeasingNotifications.AnyAsync(x=>x.AccountId==account&&x.Status==LeasingNotificationStatus.Skipped&&x.ResultKey=="LifeNotificationHistorical"),"historical notification skip status retained");}
        clock.Now=new(2028,1,16,12,0,0,TimeSpan.Zero);await processor.RunAccountAsync(account);
        await using(var db=factory.CreateDbContext()){Check(await db.LeasingNotifications.CountAsync(x=>x.AccountId==account&&x.Status==LeasingNotificationStatus.Delivered)==1,"scheduled in-app reminder reaches responsible user once");Check(!await db.LeasingNotifications.AnyAsync(x=>x.AccountId==account&&x.RecipientUserId==outsiderId&&x.Status==LeasingNotificationStatus.Delivered),"explicit extra recipient without object access never receives reminder");}
        await processor.RunAccountAsync(account);l=(await Details(a1)).Lifecycle;l.ReturnDueDate=new(2028,2,20);await owner.SaveLifecycleTermsAsync(account,a1,l,"Changed return deadline",Guid.NewGuid());await processor.RunAccountAsync(account);await using(var db=factory.CreateDbContext()){Check(!await db.LeasingNotifications.AnyAsync(x=>x.AccountId==account&&x.Status==LeasingNotificationStatus.Delivered),"changed deadline withdraws obsolete notifications");}
        var ownTasks=await owner.ListLeasingFollowupsAsync(account);var task=ownTasks.Rows.First(x=>x.AcquisitionId==a1&&x.Kind==LeasingFollowupKind.UnknownTerms||x.AcquisitionId==a2&&x.Kind==LeasingFollowupKind.UnknownTerms);await owner.UpdateLeasingFollowupAsync(account,task.Id,task.Revision,LeasingFollowupStatus.Completed,adminId,"Reviewed unknown terms",Guid.NewGuid());await processor.RunAccountAsync(account);var completed=(await owner.ListLeasingFollowupsAsync(account,status:LeasingFollowupStatus.Completed)).Rows.Single(x=>x.Id==task.Id);Check(completed.OwnerUserId==adminId&&completed.CompletedByUserId==ownerId,"completed tasks and explicit assignee survive job reruns");
        var item=initial.Acquisition.Items.Single().Id;await admin.SetCountableAsync(account,a1,item,true,"Physical devices");var replacementItem=(await Details(a2)).Acquisition.Items.Single().Id;await admin.SetCountableAsync(account,a2,replacementItem,true,"Physical devices");
        LeasingEquipment Unit(Guid line,string serial,string code)=>new(){ItemId=line,Description="Laptop",SerialNumber=serial,InternalId=code,RegisteredDate=new(2027,1,1),OwnerUserId=ownerId};
        await Reject(()=>admin.SaveEquipmentAsync(account,a1,[Unit(Guid.Empty,"S1","ASSET-1")],true,"Confirmed duplicates without selecting a line",Guid.NewGuid()),"LifeSelectEquipmentItem");
        await Deny(()=>admin.SaveEquipmentAsync(account,a1,[Unit(replacementItem,"S1","ASSET-1")],true,"Line belongs to another acquisition",Guid.NewGuid()));
        var saveRequest=Guid.NewGuid();var units=await admin.SaveEquipmentAsync(account,a1,[Unit(item,"S1","ASSET-1"),Unit(item,"S2","ASSET-2")],false,"Register",saveRequest);Check((await admin.SaveEquipmentAsync(account,a1,[],false,"Retry",saveRequest)).SequenceEqual(units),"bulk equipment retry is idempotent");
        await Reject(()=>admin.SaveEquipmentAsync(account,a1,[Unit(item,"S3","ASSET-1")],false,"Duplicate",Guid.NewGuid()),"LifeDuplicateInternalId");await Reject(()=>admin.SaveEquipmentAsync(account,a1,[Unit(item,"S1","ASSET-3")],false,"Duplicate",Guid.NewGuid()),"LifeDuplicateSerial");
        var replacement=(await admin.SaveEquipmentAsync(account,a2,[Unit(replacementItem,"S1","REPLACEMENT")],true,"Reviewed manufacturer serial duplicate",Guid.NewGuid())).Single();
        async Task<Guid> Document(Guid acquisition){var detail=await admin.GetAsync(account,acquisition,false);await admin.UploadAsync(account,acquisition,false,detail.Acquisition!.Revision,"evidence.pdf",new MemoryStream([1,2,3]));return (await Details(acquisition)).Documents.Last().Id;}
        var document=await Document(a1);
        async Task<Guid> Event(LifecycleEventInput input,bool approve=true){var id=await owner.ProposeLifecycleEventAsync(account,a1,input,Guid.NewGuid());if(approve){var e=(await Details(a1)).Events.Single(x=>x.Id==id);await admin.DecideLifecycleEventAsync(account,id,e.Revision,true,"Checked source",Guid.NewGuid());}return id;}
        var partial=await Event(new(){Kind=LeasingLifecycleKind.Return,Date=new(2028,1,16),ItemId=item,Quantity=1,Reason="Partial untracked return"});
        Check((await Details(a1)).Dispositions.Where(x=>!x.Reversed).Sum(x=>x.Quantity)==1,"partial return without serial tracking records line quantity");
        var invalid=await Event(new(){Kind=LeasingLifecycleKind.Return,Date=new(2028,1,16),ItemId=item,Quantity=2,Reason="Must select tracked units"},false);var invalidEvent=(await Details(a1)).Events.Single(x=>x.Id==invalid);await Reject(()=>admin.DecideLifecycleEventAsync(account,invalid,invalidEvent.Revision,true,"Invalid",Guid.NewGuid()),"LifeSelectUnits");
        var swap=await Event(new(){Kind=LeasingLifecycleKind.Replace,Date=new(2028,1,16),ItemId=item,EquipmentIds=[units[0]],Quantity=1,ReplacementEquipmentId=replacement,Reason="Registered replacement",SourceDocumentId=document});Check((await Details(a1)).Equipment.Single(x=>x.Id==units[0]).ReplacementEquipmentId==replacement,"replacement links existing purchased unit without new purchase effects");
        var returned=await Event(new(){Kind=LeasingLifecycleKind.Return,Date=new(2028,1,16),ItemId=item,EquipmentIds=[units[1]],Quantity=1,Reason="Tracked return"});var returnedEvent=(await Details(a1)).Events.Single(x=>x.Id==returned);await admin.ReverseLifecycleEventAsync(account,returned,returnedEvent.Revision,"Wrong unit",Guid.NewGuid());Check((await Details(a1)).Equipment.Single(x=>x.Id==units[1]).Status==LeasingEquipmentStatus.InUse&&(await Details(a1)).Dispositions.Any(x=>x.EventId==returned&&x.Reversed),"traceable latest-event reversal restores physical status and preserves history");
        await Event(new(){Kind=LeasingLifecycleKind.Buyout,Date=new(2028,1,16),ItemId=item,EquipmentIds=[units[1]],Quantity=1,BuyoutAmount=75,SourceDocumentId=document,Reason="Actual agreed buyout price"});
        await Event(new(){Kind=LeasingLifecycleKind.Return,Date=new(2028,1,16),ItemId=item,Quantity=1,Reason="Remaining untracked return"});Check((await Details(a1)).Dispositions.Where(x=>!x.Reversed).Sum(x=>x.Quantity)==4,"tracked and untracked dispositions share a single quantity ceiling");
        await Reject(()=>admin.SaveEquipmentAsync(account,a1,[Unit(item,"S4","ASSET-4")],false,"Over line quantity",Guid.NewGuid()),"LifeOverQuantity");
        var extension=await Event(new(){Kind=LeasingLifecycleKind.Extend,Date=new(2028,1,16),PreviousEndDate=new(2028,1,1),NewEndDate=new(2029,1,1),TermsReference="Continued terms with revised rent",PaymentsChanged=true,SourceDocumentId=document,Reason="Confirmed extension"});var extended=await Details(a1);Check(extended.Lifecycle.AgreedEndDate==new DateOnly(2029,1,1)&&extended.Lifecycle.OriginalEndDate==new DateOnly(2028,1,1)&&extended.Acquisition.EndDate==new DateOnly(2028,1,1)&&extended.Lifecycle.PaymentPlanReviewRequired,"extension preserves original dates and flags payment plan without calculating new amounts");
        await Reject(()=>admin.ReviewLifecycleDocumentsAsync(account,a1,extended.Lifecycle.Revision,true,true,"Needs new plan",Guid.NewGuid()),"LifePlanRevisionRequired");
        var term=new LeasingPlanTerm{Reference="EXT-1",PeriodFrom=new(2028,2,1),PeriodTo=new(2028,2,29),DueDate=new(2028,3,5),Net=100,Vat=25,Gross=125,ReviewReason="Extension documented"};var plan=await owner.SavePaymentPlanAsync(account,a1,null,[term],"Extension",LeasingPlanSource.Manual,document,Guid.NewGuid());var p=(await admin.GetPaymentsAsync(account,a1)).Plans.Single();await admin.ActivatePaymentPlanAsync(account,plan,p.Revision,"Check extension period",false,Guid.NewGuid());extended=await Details(a1);await admin.ReviewLifecycleDocumentsAsync(account,a1,extended.Lifecycle.Revision,true,true,"Revised plan activated",Guid.NewGuid());
        var revisedTerm=JsonSerializer.Deserialize<LeasingPlanTerm>(JsonSerializer.Serialize((await admin.GetPaymentsAsync(account,a1)).Terms.Single().Term))!;revisedTerm.Net=110;revisedTerm.Vat=27.5m;revisedTerm.Gross=137.5m;var newPlan=await owner.SavePaymentPlanAsync(account,a1,plan,[revisedTerm],"Updated plan",LeasingPlanSource.Manual,document,Guid.NewGuid());p=(await admin.GetPaymentsAsync(account,a1)).Plans.Single(x=>x.Id==newPlan);await admin.ActivatePaymentPlanAsync(account,newPlan,p.Revision,"Activate revision",false,Guid.NewGuid());
        var closing=await Event(new(){Kind=LeasingLifecycleKind.EarlyClose,Date=new(2028,1,16),SourceDocumentId=document,Reason="Early return agreement",UnresolvedConfirmed=false},false);var ce=(await Details(a1)).Events.Single(x=>x.Id==closing);await Reject(()=>admin.DecideLifecycleEventAsync(account,closing,ce.Revision,true,"Open invoices",Guid.NewGuid()),"LifeConfirmUnresolved");
        await Event(new(){Kind=LeasingLifecycleKind.EarlyClose,Date=new(2028,1,16),SourceDocumentId=document,Reason="Final invoices to follow",UnresolvedConfirmed=true});Check((await Details(a1)).Lifecycle.Status==LeasingLifecycleStatus.Closed&&(await Details(a1)).Acquisition.Status==LeasingAcquisitionStatus.Registered&&(await admin.GetPaymentsAsync(account,a1)).Terms.Single().Term.Gross==137.5m,"early closure keeps financial registration and future plan terms");
        var invoice=await owner.NewRentalInvoiceAsync(account,Guid.NewGuid());var ir=await owner.GetRentalInvoiceAsync(account,invoice);ir.Review.FinanceOrganizationId=party;ir.Review.Data=new(){Number="FINAL",Date=new(2028,1,16),Currency="NOK",Net=110,Vat=27.5m,Gross=137.5m,Lines=[new(){SourceId="1",Description="Final rent",Quantity=1,Price=110,Net=110,VatPercent=25,VatCategory="S"}]};ir.Review.ContentConfirmed=true;ir.Review.Allocations=[new(){InstallmentId=(await admin.GetPaymentsAsync(account,a1)).Terms.Single().Installment.Id,Net=100,Vat=25}];await owner.SaveRentalReviewAsync(account,invoice,ir.Invoice.Revision,ir.Review);ir=await admin.GetRentalInvoiceAsync(account,invoice);await admin.ApproveRentalInvoiceAsync(account,invoice,ir.Invoice.Revision);Check((await admin.GetPaymentsAsync(account,a1)).Terms.Single().InvoicedNet==100,"final invoices remain possible after lifecycle closure");
        var after=await admin.GetAsync(account,frame,true);Check(after.Used==before.Used&&after.Reserved==before.Reserved&&(await Details(a1)).Acquisition.FinancedAmount==750,"lifecycle events preserve purchase value, capacity, reservation and financing");
        var capacity=await admin.GetLeasingReportAsync(account,LeasingReportKind.Capacity,new());Check(capacity.Totals.Single(x=>x.Currency=="NOK").Used==after.Used&&capacity.Totals.Single().Reserved==after.Reserved,"capacity report uses shared live control calculations");
        var dimension=Guid.NewGuid();var tag1=Guid.NewGuid();var tag2=Guid.NewGuid();
        await using(var db=factory.CreateDbContext())
        {
            db.Dimensions.Add(new(){Id=dimension,AccountId=account,Name="Tags now renamed",Code="TAGS",AllowMultiple=true,Revision=Guid.NewGuid()});
            db.DimensionValues.AddRange(new TenantPlatform.Core.Dimensions.DimensionValue{Id=tag1,AccountId=account,DimensionId=dimension,Name="Current first",Code="A",Revision=Guid.NewGuid()},new TenantPlatform.Core.Dimensions.DimensionValue{Id=tag2,AccountId=account,DimensionId=dimension,Name="Current second",Code="B",Revision=Guid.NewGuid()});
            foreach(var tag in new[]{tag1,tag2})db.LeasingDimensionSelections.Add(new(){Id=Guid.NewGuid(),AccountId=account,ItemId=replacementItem,DimensionId=dimension,ValueId=tag,DimensionName="Original tag name",DimensionCode="TAGS",ValueName="Historical label",ValueCode=tag==tag1?"A":"B",ValuePath="Historical label"});await db.SaveChangesAsync();
        }
        var dimensions=await admin.GetLeasingReportAsync(account,LeasingReportKind.Dimensions,new(){DimensionValueId=tag1});
        Check(dimensions.Count==1&&dimensions.Totals.Single().Gross==1250&&dimensions.Rows.Single().Dimensions.Contains("Original tag name"),"multiple classification tags filter without multiplying money and retain historical names");
        var splitDimension=Guid.NewGuid();var splitValue1=Guid.NewGuid();var splitValue2=Guid.NewGuid();var splitRow1=Guid.NewGuid();var splitRow2=Guid.NewGuid();
        await using(var db=factory.CreateDbContext())
        {
            db.Dimensions.Add(new(){Id=splitDimension,AccountId=account,Name="Department",Code="DEPT",Revision=Guid.NewGuid()});
            foreach(var v in new[]{splitValue1,splitValue2})db.DimensionValues.Add(new(){Id=v,AccountId=account,DimensionId=splitDimension,Name=v.ToString(),Code=v.ToString(),Revision=Guid.NewGuid()});
            var line=await db.LeasingItems.SingleAsync(x=>x.AccountId==account&&x.Id==item);line.AllocationMode=LeasingAllocationMode.Percent;
            db.LeasingAllocationDimensions.Add(new(){AccountId=account,ItemId=item,DimensionId=splitDimension,DimensionName="Historic department",DimensionCode="DEPT"});
            db.LeasingAllocationRows.AddRange(new LeasingAllocationRow{Id=splitRow1,AccountId=account,ItemId=item,Position=0,InputValue=25},new LeasingAllocationRow{Id=splitRow2,AccountId=account,ItemId=item,Position=1,InputValue=75});
            foreach(var pair in new[]{(splitRow1,splitValue1),(splitRow2,splitValue2)})db.LeasingDimensionSelections.Add(new(){Id=Guid.NewGuid(),AccountId=account,ItemId=item,AllocationRowId=pair.Item1,DimensionId=splitDimension,ValueId=pair.Item2,DimensionName="Historic department",DimensionCode="DEPT",ValueName="Historic value",ValueCode="V",ValuePath="Historic value"});await db.SaveChangesAsync();
        }
        var splitReport=await admin.GetLeasingReportAsync(account,LeasingReportKind.Dimensions,new(){DimensionValueId=splitValue1});Check(splitReport.Count==1&&splitReport.Totals.Single().Gross==312.5m,"dimension report uses actual financial allocation rows exactly once");
        var payments=await admin.GetLeasingReportAsync(account,LeasingReportKind.Payments,new());Check(payments.Totals.Single(x=>x.Currency=="NOK").Expected==137.5m,"planned report uses only active versions without replaced-plan double counting");Check(payments.Totals.Select(x=>x.Currency).Order().SequenceEqual(new[]{"EUR","NOK"}),"report totals keep currencies separate and flag missing plans");
        var invoices=await admin.GetLeasingReportAsync(account,LeasingReportKind.InvoiceControl,new());Check(invoices.Totals.Single(x=>x.Currency=="NOK").Invoiced==125&&invoices.Totals.Single(x=>x.Currency=="NOK").Unallocated==12.5m,"invoice report separates allocated totals and document remainder exactly once");
        var dateFilter=new LeasingReportFilter{DateField=LeasingReportDate.Invoice,From=new(2028,1,16),To=new(2028,1,16)};Check((await admin.GetLeasingReportAsync(account,LeasingReportKind.InvoiceControl,dateFilter)).Totals.Single().Invoiced==125,"invoice-date filtering retains matching allocations");
        Check((await outsider.GetLeasingReportAsync(account,LeasingReportKind.Agreements,new())).Count==0,"ordinary unrelated member sees no report rows");await Deny(()=>owner.GetLeasingReportAsync(account,LeasingReportKind.Payments,new(),export:true));await Deny(()=>admin.GetLeasingReportAsync(foreignAccount,LeasingReportKind.Capacity,new(),export:true));
        var dashboard=await admin.GetLeasingDashboardAsync(account,new(2028,1,1),new(2028,12,31));Check(dashboard.Reports[LeasingReportKind.Capacity].Totals.Single().Used==capacity.Totals.Single().Used&&dashboard.Reports[LeasingReportKind.Payments].Totals.Single().Expected==137.5m,"dashboard amounts equal drill-down reports");
        using var services=new ServiceCollection().AddLogging().AddLocalization(x=>x.ResourcesPath="Resources").BuildServiceProvider();var localizer=services.GetRequiredService<IStringLocalizer<TenantPlatformResources>>();
        var exported=await admin.GetLeasingReportAsync(account,LeasingReportKind.Payments,new(){Currency="NOK"},export:true);exported.Rows[0].Name="=HYPERLINK(\"https://example.test\")";var csv=Encoding.UTF8.GetString(LeasingReportExport.Create(exported,new(){Currency="NOK"},false,localizer));Check(csv.Contains("'=HYPERLINK")&&csv.Contains("NOK"),"CSV neutralizes formula text and preserves filters");
        using(var zip=new ZipArchive(new MemoryStream(LeasingReportExport.Create(exported,new(){Currency="NOK"},true,localizer)),ZipArchiveMode.Read))
        {using var stream=zip.GetEntry("xl/worksheets/sheet1.xml")!.Open();var xml=XDocument.Load(stream);XNamespace ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";Check(!xml.Descendants(ns+"f").Any()&&xml.Descendants(ns+"c").Any(x=>(string?)x.Attribute("s")=="1")&&xml.Descendants(ns+"v").Any(x=>decimal.TryParse(x.Value,System.Globalization.NumberStyles.Number,System.Globalization.CultureInfo.InvariantCulture,out var value)&&value==137.5m),"XLSX dates and amounts are typed; user text never becomes a formula");}
        await using(var db=factory.CreateDbContext()){var m=await db.UserAccounts.SingleAsync(x=>x.AccountId==account&&x.UserId==outsiderId);db.UserAccountRoles.Add(new(){Id=Guid.NewGuid(),UserAccountId=m.Id,Role=UserRole.LeasingReportReader});await db.SaveChangesAsync();}
        Check((await outsider.GetLeasingReportAsync(account,LeasingReportKind.Agreements,new())).Count>0&&!(await outsider.GetAsync(account,frame,true)).CanEdit, "report reader can drill down without edit permission");
        Check(!(await outsider.GetPaymentsAsync(account,a1)).Permissions.CanActivate,"report read access does not grant plan approval");
        await Deny(()=>outsider.GetLeasingReportAsync(account,LeasingReportKind.Capacity,new(),export:true));
        await Deny(()=>outsider.SaveLifecycleTermsAsync(account,a1,(Details(a1).Result).Lifecycle,"No write role",Guid.NewGuid()));
        await LifecycleComponentChecks.Run(admin,account,adminId,a1,a2);
        Console.WriteLine("All phase-six lifecycle checks passed.");
    }
    sealed class MutableClock:TimeProvider{public DateTimeOffset Now{get;set;}public override DateTimeOffset GetUtcNow()=>Now;}
    static void Check(bool ok,string message){if(!ok)throw new Exception("FAIL lifecycle: "+message);Console.WriteLine("PASS lifecycle: "+message);}
    static async Task Reject(Func<Task> action,string key){try{await action();throw new Exception("Expected "+key);}catch(LeasingValidationException e)when(e.Message==key){Console.WriteLine("PASS lifecycle rejection: "+key);}}
    static async Task Deny(Func<Task> action){try{await action();throw new Exception("Expected denial");}catch(UnauthorizedAccessException){Console.WriteLine("PASS lifecycle access denied");}}
}
