<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\TenantPlatform.Core\TenantPlatform.Core.csproj" />
    <ProjectReference Include="..\TenantPlatform.Infrastructure\TenantPlatform.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
    <UserSecretsId>0e4494f0-673e-46bd-981f-6bf3adf5a8a0</UserSecretsId>
  </PropertyGroup>

</Project>
